name: app_oli
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - annotated-doc=0.0.4
  - annotated-types=0.6.0
  - anyio=4.10.0
  - aom=3.12.1
  - arrow=1.4.0
  - binaryornot=0.4.4
  - blas=1.0
  - brotlicffi=1.2.0.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.12.2
  - cairo=1.18.4
  - certifi=2025.11.12
  - cffi=2.0.0
  - chardet=5.2.0
  - charset-normalizer=3.4.4
  - click=8.2.1
  - contourpy=1.3.3
  - cookiecutter=2.6.0
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - dav1d=1.2.1
  - expat=2.7.3
  - fastapi=0.121.1
  - flet=0.24.1
  - flet-core=0.24.1
  - flet-runtime=0.24.1
  - fontconfig=2.15.0
  - fonttools=4.61.0
  - freetype=2.13.3
  - fribidi=1.0.10
  - gettext=0.21.0
  - graphite2=1.3.14
  - h11=0.16.0
  - harfbuzz=10.2.0
  - httpcore=1.0.9
  - httptools=0.7.1
  - httpx=0.28.1
  - icu=73.1
  - idna=3.11
  - intel-openmp=2025.0.0
  - jansson=2.14
  - jinja2=3.1.6
  - jpeg=9f
  - kiwisolver=1.4.9
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libabseil=20250127.0
  - libavif=1.3.0
  - libcups=2.4.15
  - libcurl=8.17.0
  - libdeflate=1.22
  - libdrm=2.4.124
  - libedit=3.1.20230828
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgl=1.7.0
  - libglib=2.84.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.2.0
  - libhwloc=2.12.1
  - libiconv=1.16
  - libidn2=2.3.8
  - libkrb5=1.21.3
  - libllvm15=15.0.7
  - libmpdec=4.0.0
  - libnghttp2=1.67.1
  - libopenjpeg=2.5.4
  - libpciaccess=0.18
  - libpng=1.6.50
  - libpq=17.6
  - libprotobuf=5.29.3
  - libsodium=1.0.20
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.7.1
  - libunistring=1.3
  - libuuid=1.41.5
  - libuv=1.48.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxkbcommon=1.9.1
  - libxml2=2.13.9
  - libzlib=1.3.1
  - lmdb=0.9.31
  - lz4-c=1.9.4
  - markdown-it-py=4.0.0
  - markupsafe=3.0.2
  - matplotlib=3.10.7
  - matplotlib-base=3.10.7
  - mdurl=0.1.2
  - mesalib=25.1.5
  - mkl=2025.0.0
  - mkl-service=2.5.2
  - mkl_fft=2.1.1
  - mkl_random=1.3.0
  - mysql=8.4.0
  - ncurses=6.5
  - numpy=2.3.5
  - numpy-base=2.3.5
  - oauthlib=3.3.1
  - openldap=2.6.10
  - openssl=3.0.18
  - packaging=23.2
  - pcre2=10.42
  - pillow=12.0.0
  - pip=25.3
  - pixman=0.46.4
  - pthread-stubs=0.3
  - pycparser=2.23
  - pydantic=2.12.4
  - pydantic-core=2.41.5
  - pygments=2.19.2
  - pyparsing=3.2.5
  - pypng=0.20220715.0
  - pyqt=6.7.1
  - pyqt6-sip=13.9.1
  - pysocks=1.7.1
  - python=3.13.10
  - python-dateutil=2.9.0post0
  - python-dotenv=1.1.0
  - python-slugify=8.0.4
  - python-tzdata=2025.2
  - python_abi=3.13
  - pyyaml=6.0.3
  - qrcode=7.4.2
  - qtbase=6.7.3
  - qtdeclarative=6.7.3
  - qtsvg=6.7.3
  - qttools=6.7.3
  - qtwebchannel=6.7.3
  - qtwebsockets=6.7.3
  - readline=8.3
  - repath=0.9.0
  - requests=2.32.5
  - rich=14.2.0
  - setuptools=80.9.0
  - sip=6.10.0
  - six=1.17.0
  - sniffio=1.3.1
  - spirv-tools=2025.1
  - sqlite=3.51.0
  - starlette=0.47.3
  - tbb=2022.3.0
  - tbb-devel=2022.3.0
  - text-unidecode=1.3
  - tk=8.6.15
  - tornado=6.5.4
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - tzdata=2025b
  - urllib3=2.6.0
  - uvicorn=0.35.0
  - uvicorn-standard=0.35.0
  - uvloop=0.22.1
  - watchdog=4.0.2
  - watchfiles=1.1.1
  - websockets=15.0.1
  - wheel=0.45.1
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.44
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxshmfence=1.3.3
  - xorg-libxxf86vm=1.1.6
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.3.1
  - zstd=1.5.7
prefix: /home/daniel/anaconda3/envs/app_oli
